import 'reflect-metadata';
import * as bcrypt from 'bcryptjs';
import { DataSource } from 'typeorm';
import {
  Application,
  Creator,
  Game,
  Media,
  MerchItem,
  News,
  Partner,
  Player,
  SiteSettings,
  Team,
  Tournament,
  User,
} from '../entities';

const ds = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST || 'localhost',
  port: parseInt(process.env.DB_PORT || '5432', 10),
  username: process.env.DB_USERNAME || 'arc',
  password: process.env.DB_PASSWORD || 'arc_secret',
  database: process.env.DB_DATABASE || 'arc_esports',
  entities: [
    Game,
    Team,
    Player,
    Creator,
    Tournament,
    News,
    Partner,
    Application,
    Media,
    SiteSettings,
    User,
    MerchItem,
  ],
  synchronize: true,
});

async function seed() {
  await ds.initialize();
  console.log('Connected to PostgreSQL');

  await ds.query(`
    TRUNCATE TABLE
      applications, media, players, teams, creators,
      tournaments, news, partners, games, site_settings,
      users, merch_items
    RESTART IDENTITY CASCADE
  `);

  const games = await ds.getRepository(Game).save([
    {
      slug: 'pubg',
      name: 'PUBG MOBILE',
      nameAr: 'ببجي موبايل',
      image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=400&fit=crop&auto=format',
      players: 12,
      tournaments: 8,
      desc: 'فريق PUBG MOBILE الرسمي لمنظمة ARC Esports',
      descEn: 'ARC Esports official PUBG MOBILE roster',
    },
    {
      slug: 'fivem',
      name: 'FiveM',
      nameAr: 'فايف إم',
      image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=400&fit=crop&auto=format',
      players: 8,
      tournaments: 4,
      desc: 'فريق FiveM المتخصص في البيئات التنافسية',
      descEn: 'ARC FiveM team specializing in competitive environments',
    },
    {
      slug: 'rocket',
      name: 'Rocket League',
      nameAr: 'روكيت ليج',
      image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=400&fit=crop&auto=format',
      players: 6,
      tournaments: 5,
      desc: 'فريق Rocket League ذو الأداء العالي',
      descEn: 'High-performance ARC Rocket League team',
    },
  ]);

  const teams = await ds.getRepository(Team).save([
    {
      name: 'ARC PUBG Alpha',
      game: 'PUBG MOBILE',
      gameId: games[0].id,
      logo: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=100&h=100&fit=crop&auto=format',
      players: 6,
      captain: 'XShadow',
      achievements: ['بطل الخليج 2024', 'المركز الثالث MENA 2023'],
      achievementsEn: ['Gulf Champion 2024', '3rd Place MENA 2023'],
      tournaments: ['ARC Open S1', 'Gulf League S3', 'MENA Pro Series'],
    },
    {
      name: 'ARC PUBG Beta',
      game: 'PUBG MOBILE',
      gameId: games[0].id,
      logo: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=100&h=100&fit=crop&auto=format',
      players: 5,
      captain: 'SnipeKing',
      achievements: ['المركز الثاني ARC Open S2'],
      achievementsEn: ['2nd Place ARC Open S2'],
      tournaments: ['ARC Open S2', 'Saudi League'],
    },
    {
      name: 'ARC FiveM Crew',
      game: 'FiveM',
      gameId: games[1].id,
      logo: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=100&h=100&fit=crop&auto=format',
      players: 8,
      captain: 'CityKing99',
      achievements: ['أفضل منظمة RP 2024'],
      achievementsEn: ['Best RP Organization 2024'],
      tournaments: ['ARC RP Cup', 'City Wars'],
    },
    {
      name: 'ARC Rocket',
      game: 'Rocket League',
      gameId: games[2].id,
      logo: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=100&h=100&fit=crop&auto=format',
      players: 3,
      captain: 'RocketGod',
      achievements: ['بطل ARC RL Cup 2024'],
      achievementsEn: ['ARC RL Cup Champion 2024'],
      tournaments: ['ARC RL Cup', 'Gulf RL Series'],
    },
  ]);

  await ds.getRepository(Player).save([
    {
      name: 'XShadow',
      game: 'PUBG MOBILE',
      gameId: games[0].id,
      teamId: teams[0].id,
      country: 'السعودية',
      countryEn: 'Saudi Arabia',
      flag: '🇸🇦',
      role: 'IGL',
      rank: 'Conqueror',
      image: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=300&h=300&fit=crop&auto=format',
      achievements: ['بطل الخليج 2024'],
      achievementsEn: ['Gulf Champion 2024'],
      social: { twitter: 'https://x.com/xshadow', instagram: 'https://instagram.com/xshadow' },
    },
    {
      name: 'SnipeKing',
      game: 'PUBG MOBILE',
      gameId: games[0].id,
      teamId: teams[1].id,
      country: 'الإمارات',
      countryEn: 'UAE',
      flag: '🇦🇪',
      role: 'Sniper',
      rank: 'Conqueror',
      image: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=300&h=300&fit=crop&auto=format',
      achievements: ['أفضل قناص MENA 2023'],
      achievementsEn: ['Best Sniper MENA 2023'],
      social: { twitter: 'https://x.com/snipeking', instagram: 'https://instagram.com/snipeking' },
    },
    {
      name: 'FragMaster',
      game: 'PUBG MOBILE',
      gameId: games[0].id,
      teamId: teams[0].id,
      country: 'الكويت',
      countryEn: 'Kuwait',
      flag: '🇰🇼',
      role: 'Fragger',
      rank: 'Ace',
      image: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=300&h=300&fit=crop&auto=format',
      achievements: ['MVP ARC Open S1'],
      achievementsEn: ['MVP ARC Open S1'],
      social: { twitter: 'https://x.com/fragmaster', instagram: 'https://instagram.com/fragmaster' },
    },
    {
      name: 'CityKing99',
      game: 'FiveM',
      gameId: games[1].id,
      teamId: teams[2].id,
      country: 'قطر',
      countryEn: 'Qatar',
      flag: '🇶🇦',
      role: 'Entry Fragger',
      rank: 'Pro',
      image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&auto=format',
      achievements: ['أفضل لاعب FiveM 2024'],
      achievementsEn: ['Best FiveM Player 2024'],
      social: { twitter: 'https://x.com/cityking99', instagram: 'https://instagram.com/cityking99' },
    },
    {
      name: 'RocketGod',
      game: 'Rocket League',
      gameId: games[2].id,
      teamId: teams[3].id,
      country: 'البحرين',
      countryEn: 'Bahrain',
      flag: '🇧🇭',
      role: 'Striker',
      rank: 'Grand Champion',
      image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&auto=format',
      achievements: ['بطل ARC RL Cup'],
      achievementsEn: ['ARC RL Cup Champion'],
      social: { twitter: 'https://x.com/rocketgod', instagram: 'https://instagram.com/rocketgod' },
    },
    {
      name: 'GhostAssassin',
      game: 'PUBG MOBILE',
      gameId: games[0].id,
      teamId: teams[0].id,
      country: 'مصر',
      countryEn: 'Egypt',
      flag: '🇪🇬',
      role: 'Support',
      rank: 'Conqueror',
      image: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=300&h=300&fit=crop&auto=format',
      achievements: ['أفضل Support 2024'],
      achievementsEn: ['Best Support 2024'],
      social: { twitter: 'https://x.com/ghostassassin', instagram: 'https://instagram.com/ghostassassin' },
    },
  ]);

  await ds.getRepository(Creator).save([
    {
      name: 'TurboGamer',
      nameAr: 'تيربو جيمر',
      bio: 'صانع محتوى متخصص في PUBG MOBILE مع أكثر من 5 سنوات خبرة',
      bioEn: 'PUBG MOBILE content creator with 5+ years experience',
      image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&auto=format',
      verified: true,
      platforms: { tiktok: '850K', youtube: '120K', twitch: '15K', kick: '8K' },
      social: {
        tiktok: 'https://tiktok.com/@turbogamer',
        youtube: 'https://youtube.com/@turbogamer',
        twitch: 'https://twitch.tv/turbogamer',
        kick: 'https://kick.com/turbogamer',
      },
    },
    {
      name: 'NightStream',
      nameAr: 'نايت ستريم',
      bio: 'بث مباشر يومي، متخصص في FiveM وتجارب الرول بلاي',
      bioEn: 'Daily livestreamer specializing in FiveM and roleplay experiences',
      image: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=300&h=300&fit=crop&auto=format',
      verified: true,
      platforms: { tiktok: '420K', youtube: '65K', twitch: '22K', kick: '5K' },
      social: {
        tiktok: 'https://tiktok.com/@nightstream',
        youtube: 'https://youtube.com/@nightstream',
        twitch: 'https://twitch.tv/nightstream',
        kick: 'https://kick.com/nightstream',
      },
    },
    {
      name: 'AimLegend',
      nameAr: 'ايم ليجيند',
      bio: 'محتوى تعليمي واحترافي في PUBG MOBILE',
      bioEn: 'Educational and competitive PUBG MOBILE content',
      image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=300&fit=crop&auto=format',
      verified: false,
      platforms: { tiktok: '310K', youtube: '45K', twitch: '7K', kick: '3K' },
      social: {
        tiktok: 'https://tiktok.com/@aimlegend',
        youtube: 'https://youtube.com/@aimlegend',
        twitch: 'https://twitch.tv/aimlegend',
        kick: 'https://kick.com/aimlegend',
      },
    },
  ]);

  await ds.getRepository(Tournament).save([
    {
      name: 'ARC Open Championship S3',
      nameAr: 'بطولة ARC المفتوحة الموسم 3',
      status: 'active',
      image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=350&fit=crop&auto=format',
      game: 'PUBG MOBILE',
      startDate: '2026-07-15',
      endDate: '2026-07-30',
      prize: '$5,000',
      teams: 32,
    },
    {
      name: 'ARC Rocket League Cup',
      nameAr: 'كأس ARC للروكيت ليج',
      status: 'upcoming',
      image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=350&fit=crop&auto=format',
      game: 'Rocket League',
      startDate: '2026-09-05',
      endDate: '2026-09-10',
      prize: '$2,000',
      teams: 16,
    },
    {
      name: 'ARC Open Championship S2',
      nameAr: 'بطولة ARC المفتوحة الموسم 2',
      status: 'past',
      image: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=600&h=350&fit=crop&auto=format',
      game: 'PUBG MOBILE',
      startDate: '2026-05-01',
      endDate: '2026-05-15',
      prize: '$3,000',
      teams: 24,
    },
    {
      name: 'ARC FiveM City Wars',
      nameAr: 'حرب المدن ARC',
      status: 'past',
      image: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=350&fit=crop&auto=format',
      game: 'FiveM',
      startDate: '2026-03-20',
      endDate: '2026-03-25',
      prize: '$1,500',
      teams: 12,
    },
  ]);

  await ds.getRepository(News).save([
    {
      title: 'ARC Esports تتوج بلقب بطولة الخليج 2024',
      titleEn: 'ARC Esports Wins Gulf Championship 2024',
      summary: 'حققت منظمة ARC Esports لقبها الأول في بطولة الخليج للألعاب الإلكترونية بأداء مبهر',
      summaryEn: 'ARC Esports wins their first Gulf Championship title with an incredible performance',
      date: '2026-07-20',
      category: 'إنجازات',
      categoryEn: 'Achievements',
      image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&h=300&fit=crop&auto=format',
    },
    {
      title: 'انضمام XShadow قائداً لفريق PUBG Alpha',
      titleEn: 'XShadow Joins as PUBG Alpha Team Captain',
      summary: 'يسعدنا الإعلان عن انضمام اللاعب المخضرم XShadow إلى عائلة ARC Esports',
      summaryEn: 'We are pleased to announce the signing of veteran player XShadow to the ARC Esports family',
      date: '2026-07-15',
      category: 'انتقالات',
      categoryEn: 'Transfers',
      image: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=500&h=300&fit=crop&auto=format',
    },
    {
      title: 'ARC Open Championship S3 — التسجيل مفتوح',
      titleEn: 'ARC Open Championship S3 — Registration Open',
      summary: 'يسر منظمة ARC الإعلان عن فتح باب التسجيل في بطولتها الكبرى للموسم الثالث',
      summaryEn: 'ARC Organization is pleased to announce the opening of registration for its major third season tournament',
      date: '2026-07-10',
      category: 'بطولات',
      categoryEn: 'Tournaments',
      image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=500&h=300&fit=crop&auto=format',
    },
  ]);

  await ds.getRepository(Partner).save([
    { name: 'NVIDIA', logo: 'NVIDIA', url: 'https://nvidia.com', sortOrder: 1 },
    { name: 'STC', logo: 'STC', url: 'https://stc.com.sa', sortOrder: 2 },
    { name: 'Razer', logo: 'RAZER', url: 'https://razer.com', sortOrder: 3 },
    { name: 'HyperX', logo: 'HyperX', url: 'https://hyperx.com', sortOrder: 4 },
    { name: 'Logitech G', logo: 'LOGITECH G', url: 'https://logitechg.com', sortOrder: 5 },
    { name: 'Monster Energy', logo: 'MONSTER', url: 'https://monsterenergy.com', sortOrder: 6 },
  ]);

  await ds.getRepository(Media).save([
    {
      title: 'Gulf Championship Final Highlights',
      titleAr: 'أبرز لقطات نهائي بطولة الخليج',
      thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=600&h=340&fit=crop&auto=format',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      category: 'highlights',
      creator: 'ARC Official',
    },
    {
      title: 'TurboGamer — Rank Push Session',
      titleAr: 'تيربو جيمر — جلسة رفع الرتبة',
      thumbnail: 'https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=600&h=340&fit=crop&auto=format',
      videoUrl: 'https://www.twitch.tv/turbogamer',
      category: 'creators',
      creator: 'TurboGamer',
    },
    {
      title: 'ARC Open S3 Trailer',
      titleAr: 'إعلان بطولة ARC المفتوحة الموسم 3',
      thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&h=340&fit=crop&auto=format',
      videoUrl: 'https://www.youtube.com/@arcesports',
      category: 'tournaments',
      creator: 'ARC Official',
    },
    {
      title: 'Team Alpha Scrim Clips',
      titleAr: 'لقطات تدريب فريق Alpha',
      thumbnail: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?w=600&h=340&fit=crop&auto=format',
      videoUrl: 'https://www.youtube.com/@arcesports',
      category: 'latest',
      creator: 'ARC Official',
    },
  ]);

  await ds.getRepository(Application).save([
    {
      type: 'player',
      status: 'pending',
      name: 'Ahmed Al-Rashid',
      email: 'ahmed@example.com',
      discord: 'ahmed#1234',
      country: 'SA',
      age: 22,
      game: 'PUBG MOBILE',
      role: 'IGL',
      accountId: 'ARC-AHMED-01',
      achievements: 'Top 10 MENA ranked multiple seasons',
    },
    {
      type: 'player',
      status: 'approved',
      name: 'Omar Khalid',
      email: 'omar@example.com',
      discord: 'omar#5678',
      country: 'AE',
      age: 20,
      game: 'Rocket League',
      role: 'Striker',
      accountId: 'ARC-OMAR-RL',
    },
    {
      type: 'player',
      status: 'rejected',
      name: 'Faisal Al-Mutairi',
      email: 'faisal@example.com',
      discord: 'faisal#9012',
      country: 'KW',
      age: 19,
      game: 'PUBG MOBILE',
      role: 'Fragger',
      accountId: 'ARC-FAISAL',
      adminNotes: 'Incomplete application',
    },
    {
      type: 'player',
      status: 'pending',
      name: 'Khalid Hassan',
      email: 'khalid@example.com',
      discord: 'khalid#3344',
      country: 'QA',
      age: 24,
      game: 'FiveM',
      role: 'Entry Fragger',
      accountId: 'ARC-KHALID',
    },
    {
      type: 'team',
      status: 'pending',
      name: 'Desert Eagles',
      teamName: 'Desert Eagles',
      game: 'PUBG MOBILE',
      captain: 'DesertKing',
      playerCount: 5,
      email: 'desert@example.com',
      discord: 'desert#1111',
      country: 'SA',
    },
    {
      type: 'team',
      status: 'approved',
      name: 'Storm Riders',
      teamName: 'Storm Riders',
      game: 'Rocket League',
      captain: 'StormBolt',
      playerCount: 3,
      email: 'storm@example.com',
      discord: 'storm#2222',
      country: 'AE',
    },
    {
      type: 'creator',
      status: 'pending',
      name: 'GamersZone',
      platform: 'TikTok',
      followers: '450K',
      email: 'gz@example.com',
      discord: 'gz#3333',
      country: 'SA',
      platforms: { tiktok: '450K', youtube: '20K', twitch: '2K', kick: '1K' },
      social: { tiktok: 'https://tiktok.com/@gamerszone' },
    },
    {
      type: 'creator',
      status: 'approved',
      name: 'ProStream99',
      platform: 'Twitch',
      followers: '12K',
      email: 'pro@example.com',
      discord: 'pro#4444',
      country: 'EG',
      platforms: { tiktok: '8K', youtube: '5K', twitch: '12K', kick: '900' },
    },
    {
      type: 'creator',
      status: 'rejected',
      name: 'EsportsAra',
      platform: 'YouTube',
      followers: '85K',
      email: 'ara@example.com',
      discord: 'ara#5555',
      country: 'SA',
      platforms: { youtube: '85K' },
      adminNotes: 'Does not meet activity requirements',
    },
  ]);

  await ds.getRepository(SiteSettings).save({
    brandName: 'ARC Esports',
    taglineAr: 'نصنع الأبطال… ونبني مستقبل صناع المحتوى.',
    taglineEn: 'We create champions… and build the future of content creators.',
    social: {
      discord: 'https://discord.gg/arcesports',
      tiktok: 'https://tiktok.com/@arcesports',
      youtube: 'https://youtube.com/@arcesports',
      kick: 'https://kick.com/arcesports',
      twitch: 'https://twitch.tv/arcesports',
      email: 'contact@arcesports.com',
    },
    stats: { players: 26, teams: 4, creators: 3, tournaments: 17 },
    contactEmail: 'contact@arcesports.com',
  });

  const adminEmail = (process.env.ADMIN_EMAIL || 'madunitesp@gmail.com').toLowerCase();
  const adminPassword = process.env.ADMIN_PASSWORD || '494930Mm';
  const adminName = process.env.ADMIN_NAME || 'ARC Admin';
  const passwordHash = await bcrypt.hash(adminPassword, 10);
  await ds.getRepository(User).save({
    email: adminEmail,
    passwordHash,
    name: adminName,
    role: 'admin',
    active: true,
  });

  await ds.getRepository(MerchItem).save([
    {
      name: 'ARC Pro Jersey',
      nameAr: 'جيرسي ARC الاحترافي',
      description: 'Official match jersey with ARC crest, breathable fabric, and orange accent panels.',
      descriptionAr: 'جيرسي المباريات الرسمي بشعار ARC، قماش تنفسي، وتفاصيل برتقالية مميزة.',
      category: 'jersey',
      price: '249 SAR',
      image: 'https://images.unsplash.com/photo-1517649763962-0c623066027b?w=700&h=800&fit=crop&auto=format',
      colors: ['#0B3C6D', '#0D1117', '#F7941D'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      featured: true,
      available: true,
      sortOrder: 1,
    },
    {
      name: 'ARC Away Kit',
      nameAr: 'طقم ARC الضيف',
      description: 'Away performance kit with navy base and ARC brand mark embroidery.',
      descriptionAr: 'طقم الضيف بأساس كحلي وتطريز شعار ARC الرسمي.',
      category: 'jersey',
      price: '229 SAR',
      image: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?w=700&h=800&fit=crop&auto=format',
      colors: ['#174C8F', '#FFFFFF'],
      sizes: ['S', 'M', 'L', 'XL'],
      featured: true,
      available: true,
      sortOrder: 2,
    },
    {
      name: 'ARC Legacy Hoodie',
      nameAr: 'هودي ARC Legacy',
      description: 'Premium heavyweight hoodie with glass-effect print and orange zipper accents.',
      descriptionAr: 'هودي فاخر بطبعة زجاجية وتفاصيل سحاب برتقالية.',
      category: 'hoodie',
      price: '299 SAR',
      image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=700&h=800&fit=crop&auto=format',
      colors: ['#0D1117', '#0B3C6D'],
      sizes: ['M', 'L', 'XL', 'XXL'],
      featured: true,
      available: true,
      sortOrder: 3,
    },
    {
      name: 'ARC Cap',
      nameAr: 'قبعة ARC',
      description: 'Structured cap with embossed ARC logo and moisture-wicking sweatband.',
      descriptionAr: 'قبعة منظمة بشعار ARC البارز وشريط داخلي ماص للرطوبة.',
      category: 'cap',
      price: '99 SAR',
      image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=700&h=800&fit=crop&auto=format',
      colors: ['#0B3C6D', '#F7941D'],
      sizes: ['One Size'],
      featured: false,
      available: true,
      sortOrder: 4,
    },
    {
      name: 'ARC Wristband Set',
      nameAr: 'سوارات ARC',
      description: 'Dual wristband set in official ARC blue and orange for match day.',
      descriptionAr: 'طقم سوارين بألوان ARC الرسمية للأزرق والبرتقالي.',
      category: 'accessory',
      price: '49 SAR',
      image: 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=700&h=800&fit=crop&auto=format',
      colors: ['#0B3C6D', '#F7941D'],
      sizes: ['One Size'],
      featured: false,
      available: true,
      sortOrder: 5,
    },
  ]);

  console.log(`Admin seeded: ${adminEmail}`);
  console.log('Seed completed successfully');
  await ds.destroy();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
